### ISSUE TITLE
Fehler in Stud.IP 3.4.3 und 3.5

### ISSUE THREAD

**Issue by tthelen** [Krassmus/LernmodulePlugin#1]
Mit den aktuellen Release-Versionen von Stud.IP 3.4 und 3.5 erscheint an verschiedenen Stellen (Meine Seminare, Veranstaltungsadministration, Lernmodul hinzufügen) efolgende Fehlermeldung:

Fehler! Bitte wenden Sie sich an Ihren Systemadministrator.
    Passed variable is not an array or object

lt. stack trace ist ein NULL-Parameter für ein JSONArrayObject schuld.

Der im trunk enthaltene Fix aus https://develop.studip.de/trac/ticket/7334 behebt das Problem.

**Comment by Krassmus** [comment]
Das liegt ja an einem schon gefixten Problem in Stud.IP. Ich denke, ich schließe das Ticket wieder. Aber danke Dir.
